name: Auto Post to WordPress

# 수동 실행과 스케줄 실행 둘 다 가능하게 설정
on:
  schedule:
    - cron: "0 6 * * *"  # 매일 아침 6시에 자동 실행 (UTC 기준)
  workflow_dispatch:  # 수동 실행을 위한 트리거

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.6'  # Python 3.12.6 버전 설정

    - name: Install dependencies
      run: |
        pip install openai python-wordpress-xmlrpc schedule

    - name: Run the Python script
      run: |
        python auto_post.py
