name: Auto Post to WordPress

on:
  schedule:
    - cron: "0 21 * * *"  # 매일 한국 시간 아침 6시에 실행 (UTC 기준 21시)
  workflow_dispatch:  # 수동 실행을 위한 트리거

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.6'  # Python 3.12.6 버전 설정

    - name: Install dependencies
      run: |
        pip install openai python-wordpress-xmlrpc requests

    - name: Run the Python script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        WP_USERNAME: ${{ secrets.WP_USERNAME }}
        WP_PASSWORD: ${{ secrets.WP_PASSWORD }}
      run: |
        python auto_post.py
