name: Auto Post to WordPress

# 매일 아침 6시에 자동으로 실행되도록 설정
on:
  schedule:
    - cron: "0 6 * * *"  # UTC 기준 아침 6시 (한국 시간은 UTC+9)
  workflow_dispatch:  # 수동 실행을 위한 트리거

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.6'  # Python 3.12.6 버전 설정

    - name: Install dependencies
      run: |
        pip install openai python-wordpress-xmlrpc schedule requests  # 필요한 모듈 설치

    - name: Run the Python script
      run: |
        python auto_post.py  # Python 스크립트 실행
